### ISSUE TITLE
full screen landscape web app

### ISSUE THREAD

**Issue by ethanrublee** [farm-ng/tractor#14]
I've mounted my phone to the joystick in landscape mode.

Would be nice if the app could go full screen (with no address bar), and be optimized for good in landscape.

On android, I can click the chrome settings and add a launcher easily to the home screen, and according to this guide, the app when launched from the home screen can come up in full screen mode:
https://developers.google.com/web/fundamentals/native-hardware/fullscreen

![IMG_20200422_232937](https://user-images.githubusercontent.com/153678/80285894-ea4c0880-86dc-11ea-9f23-31c9a1e380d5.jpg)

![IMG_20200422_232930 (1)](https://user-images.githubusercontent.com/153678/80285893-e91adb80-86dc-11ea-855c-3540cb619df8.jpg)

**Comment by mabitter** [comment]
@ethanrublee - I will have some cycles today (& more later in the week) and am thinking to take a bite into this and see how much I can chew up and spit back.  Following your lead, i'm looking at '[screenful](https://github.com/sindresorhus/screenfull.js)' as a solution.  Check out the [demo](https://sindresorhus.com/screenfull.js) link if you haven't already, the unicorn fullscreen is pretty awesome.  Hollar if you think I should bail out on this particular path of implementation, otherwise i'll fork and create branch 'frontend-screenfull' and see how well I can start to lay things out for the primary use case of a mobile device in landscape orientation.

**Comment by ethanrublee** [comment]
Sounds good. Go for it.
